package presentacion.vistas.componentes;

import dtos.ResidenteDTO;
import java.awt.Dimension;
import java.awt.Font;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.SwingWorker;
import javax.swing.Timer;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import objetosnegocio.ResidenteBO;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author abrilislas
 */
public class BuscadorResidentes extends javax.swing.JPanel {
    
    String PLACEHOLDER_TEXT = "Ingresa un nombre o ID";
    
    //modelo donde almacenamos la data
    DefaultListModel<String> listModel = new DefaultListModel<>();
    ResidenteBO residenteBO = ResidenteBO.getInstance();
    private Timer timer;


    /**
     * Creates new form BuscadorResidentes
     * le puse las dimensiones como parametro, aun no lo implemento
     * para que se adapte segun la pantalla que lo ocupe
     * @param width
     * @param height
     */
    public BuscadorResidentes(int width, int height) {
        initComponents();
        setSize(new Dimension(width, height));
        aplicarEstilos();
        configurarBuscador();
        popupMenu.add(searchResults);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        searchResults = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        buscadorResidentesInput = new javax.swing.JTextField();

        searchResults.setLayout(new java.awt.BorderLayout());

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        searchResults.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        setLayout(new java.awt.BorderLayout());

        buscadorResidentesInput.setFont(new java.awt.Font("Hei", 1, 18)); // NOI18N
        buscadorResidentesInput.setForeground(new java.awt.Color(204, 204, 204));
        buscadorResidentesInput.setText("Ingresa un nombre o id");
        buscadorResidentesInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscadorResidentesInputActionPerformed(evt);
            }
        });
        buscadorResidentesInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscadorResidentesInputKeyReleased(evt);
            }
        });
        add(buscadorResidentesInput, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void buscadorResidentesInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscadorResidentesInputActionPerformed
    }//GEN-LAST:event_buscadorResidentesInputActionPerformed

    private void buscadorResidentesInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscadorResidentesInputKeyReleased

    }//GEN-LAST:event_buscadorResidentesInputKeyReleased
    
    private void buscar() {
        String texto = buscadorResidentesInput.getText().trim();
        
        if(texto.equals(PLACEHOLDER_TEXT)){
            popupMenu.setVisible(false);
            return;
        }
      
        if(texto.length() < 2){
            popupMenu.setVisible(false);
            return;
        }
        if(!texto.matches("[a-zA-Z0-9áéíóúÁÉÍÓÚñÑ\\s]+") && !texto.equals(PLACEHOLDER_TEXT)){
            mostrarMensaje("Entrada inválida");
            return;
        }
        
        // sanitizacion de entradas
        texto = texto.toLowerCase(); 
        final String fintalTexto = texto.replaceAll("[^a-zA-Z0-9áéíóúÁÉÍÓÚñÑ\\s]", "");

        new SwingWorker<List<ResidenteDTO>, Void>() {

        @Override
        protected List<ResidenteDTO> doInBackground() throws Exception {
                return residenteBO.getResidentesBusqueda(fintalTexto);
            }

            @Override
            protected void done() {
                    try {
                        List<ResidenteDTO> lista = get();
                        listModel.clear();

                        if (lista.isEmpty()) {
                            mostrarMensaje("No se encontraron resultados");
                            return;
                        }

                        for (ResidenteDTO residente : lista) {
                            String nombre = residente.getNombre() + " "
                                    + residente.getApellido_paterno() + " "
                                    + residente.getApellido_materno();

                            listModel.addElement(nombre);
                        }

                        popupMenu.setPreferredSize(new Dimension(
                            buscadorResidentesInput.getWidth(),
                            200));

                        popupMenu.show(buscadorResidentesInput, 0, buscadorResidentesInput.getHeight());

                    } catch (Exception e) {
                        if(fintalTexto.equals(PLACEHOLDER_TEXT)){
                            popupMenu.setVisible(false);
                        }else{
                            mostrarMensaje("Ha ocurrido un error");
                        }
                }
            }
        }.execute();
    }
    
    private void configurarBuscador() {
        timer = new Timer(200, e -> buscar()); 
        timer.setRepeats(false);

        buscadorResidentesInput.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) { reiniciarTimer(); }
            public void removeUpdate(DocumentEvent e) { reiniciarTimer(); }
            public void changedUpdate(DocumentEvent e) { reiniciarTimer(); }

            private void reiniciarTimer() {
                timer.restart();
            }
        });
    }
    
    private void mostrarMensaje(String mensaje) {
        listModel.clear();
        listModel.addElement(mensaje);
        popupMenu.setPreferredSize(new Dimension(
            buscadorResidentesInput.getWidth(),
            45
        ));

        popupMenu.revalidate();
        popupMenu.repaint();

        popupMenu.show(buscadorResidentesInput, 0, buscadorResidentesInput.getHeight());
    }

    
    
    private void aplicarEstilos() {

        buscadorResidentesInput.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        buscadorResidentesInput.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 1, true),
            javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)
        ));
        buscadorResidentesInput.setCaretColor(new java.awt.Color(0, 102, 204));

        // focus
        buscadorResidentesInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                buscadorResidentesInput.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                    javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204), 1, true),
                    javax.swing.BorderFactory.createEmptyBorder(7, 11, 7, 11)
                ));
                buscadorResidentesInput.setForeground(new java.awt.Color(40, 40, 40));
                buscadorResidentesInput.setText("");
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                buscadorResidentesInput.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                    javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 0, true),
                    javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)
                ));
                buscadorResidentesInput.setText(PLACEHOLDER_TEXT);
                buscadorResidentesInput.setForeground(new java.awt.Color(204, 204, 204));
            }
        });

        // popup
        popupMenu.setFocusable(false);
        popupMenu.setBackground(new java.awt.Color(250, 250, 250));
        popupMenu.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220,220,220), 1, true),
            javax.swing.BorderFactory.createEmptyBorder(5,5,5,5)
        ));

        searchResults.setBackground(java.awt.Color.WHITE);

        //lista
        jList1.setModel(listModel);
        jList1.setBackground(java.awt.Color.WHITE);
        jList1.setFixedCellHeight(35);
        jList1.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jScrollPane1.setBorder(null);
        jScrollPane1.setVisible(true);
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscadorResidentesInput;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu popupMenu;
    private javax.swing.JPanel searchResults;
    // End of variables declaration//GEN-END:variables
}
