package presentacion.vistas.componentes;

import dtos.ResidenteDTO;
import java.util.List;
import javax.swing.DefaultListModel;
import objetosnegocio.ResidenteBO;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author abrilislas
 */
public class BuscadorResidentes extends javax.swing.JPanel {
    
    //modelo donde almacenamos la data
    DefaultListModel<String> listModel = new DefaultListModel<>();
    ResidenteBO residenteBO = ResidenteBO.getInstance();

    /**
     * Creates new form BuscadorResidentes
     * le puse las dimensiones como parametro, aun no lo implemento
     * para que se adapte segun la pantalla que lo ocupe
     * @param width
     * @param height
     */
    public BuscadorResidentes(int width, int height) {
        initComponents();
        setSize(width,height);
        this.buscadorResidentesInput.setSize(width,height);
        this.popupMenu.add(searchResults);
        this.popupMenu.setSize(width,height);
        jList1.setModel(listModel);
        popupMenu.setFocusable(false);
        setVisible(true);
        
        buscadorResidentesInput.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {

            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                buscar();
            }

            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                buscar();
            }

            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                buscar();
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        searchResults = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        buscadorResidentesInput = new javax.swing.JTextField();

        searchResults.setLayout(new java.awt.BorderLayout());

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        searchResults.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        buscadorResidentesInput.setFont(new java.awt.Font("Hei", 1, 18)); // NOI18N
        buscadorResidentesInput.setForeground(new java.awt.Color(51, 123, 194));
        buscadorResidentesInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscadorResidentesInputActionPerformed(evt);
            }
        });
        buscadorResidentesInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscadorResidentesInputKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(buscadorResidentesInput, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(buscadorResidentesInput, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buscadorResidentesInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscadorResidentesInputActionPerformed
    }//GEN-LAST:event_buscadorResidentesInputActionPerformed

    private void buscadorResidentesInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscadorResidentesInputKeyReleased

    }//GEN-LAST:event_buscadorResidentesInputKeyReleased
    
    private void buscar() {
        String texto = buscadorResidentesInput.getText();

        if(texto.length() < 0){
            popupMenu.setVisible(false);
            return;
        }

        popupMenu.show(buscadorResidentesInput, 0, buscadorResidentesInput.getHeight());

        try {
            listModel.clear();

            List<ResidenteDTO> listaResidentes = residenteBO.getResidentesBusqueda(texto);

            for (ResidenteDTO residente : listaResidentes) {
                String nombreResidente = residente.getNombre() + " "
                        + residente.getApellido_paterno() + " "
                        + residente.getApellido_materno();

                listModel.addElement(nombreResidente);
            }

        }   catch(Exception ex){
                ex.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscadorResidentesInput;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu popupMenu;
    private javax.swing.JPanel searchResults;
    // End of variables declaration//GEN-END:variables
}
